# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Woolen Yeti
email: woolenyeti@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a site with hopes to some day become a real blog. It may look like a lot of dummy text now, but come back later for some crochet posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
social:
  instagram:
    label: Instagram
    title: "Instagram: Go to Woolen Yeti's Instagram Page"
    url: instagram.com/woolenyeti
    full: https://instagram.com/woolenyeti
  etsy:
    label: Etsy
    title: "Etsy: Shop Woolen Yeti's on Etsy"
    url: etsy.com/shop/woolenyeti
    full: https://etsy.com/shop/woolenyeti
  ravelry:
    label: Ravelry
    title: "Ravelry: Go to my Ravelry page"
    url: ravelry.com/people/Mirananemone
    full: https://ravelry.com/people/Mirananemone
  youtube:
    label: YouTube
    title: "YouTube: See Woolen Yeti videos on Youtube"
    url: youtube.com/channel/UCzlMHqGJfkpiS6EIwCp2eMg
    full: https://www.youtube.com/channel/UCzlMHqGJfkpiS6EIwCp2eMg
  rss:
    label: RSS
    title: "Subscribe via RSS"
    url: /feed.xml
    full: /feed.xml

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "wrapper"
      author: "Miranda Hoover"
      popupSignup: false
      blockSignup: true
      includeTitle: true
      restrictWidth: true
  -
    scope:
      path: "content/_posts"
    values:
      layout: post
      comments: true
      tags: post
      permalink: posts/:title/

  -
    scope:
      path: "content/_posts/posts"
    values:
      tags: post
      categories: posts
      permalink: posts/:title/

  -
    scope:
      path: "content/_posts/patterns"
    values:
      layout: pattern
      tags: pattern
      categories: patterns
      permalink: patterns/:title/

  -
    scope:
      path: "content/_posts/techniques"
    values:
      tags: techniques
      categories: techniques
      permalink: techniques/:title/


##########################
# Jekyll Compose Config #
########################
# Go to ~/Gemfile for details
jekyll_compose:



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - src/
  - gulp/
  - working/
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - webpack.*
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
