# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wool's End
email: woolsendpatterns@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a site with hopes to some day become a real blog. It may look like a lot of dummy text now, but come back later for some crochet posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Miranda Hoover"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      tags: post

  -
    scope:
      path: "_posts/patterns"
    values:
      tags: pattern

  -
    scope:
      path: "_posts/videos"
    values:
      tags: videos

permalink: pretty

collections:
  posts:
    output: true
    permalink: /:collection/:title/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - src/
  - gulp/
  - working/
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - webpack.*
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
